---
title: "An Intro to Preprints for Early Career Hydrologists"
author: "Sheila Saia"
date: 2019-05-20T21:12:00-05:00
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

When I attended the 2019 [American Geophysical Union (AGU)](https://sites.agu.org/) this past December in Washington, DC, I had the pleasure of meeting members of an international organization of early career hydrologists called the [Young Hydrologic Society (YHS)](https://younghs.com/). To clarify, "young" here refers to early career, rather than age. I was interested in getting more involved in the organization and thought writing a blog post for the group's website would be a great way for me to contribute. I had recently lead a discussion on preprints with peers back in North Carolina and thought a blog post on this topic would be a perfect opportunity to continue that discussion. I also had (and still have) a lot of questions regarding preprints and hoped that preparing the blog post would give the opportunity to answer these questions.

# Goals of This Post

The blog post that follows is re-posted of the YHS article I wrote on preprints. You can find the original article [here](https://younghs.com/2019/05/20/an-introduction-to-preprints-for-early-career-hydrologists/).

Thanks to H. Beria, C. Hall, S. Harrigan, C. Jackson, and N. Krell for their helpful feedback on this post.

# Introduction

Growing calls for open and reproducible research across science, technology, engineering, and math (STEM) disciplines have advanced the conversation around preprints (e.g., Schloss, 2017; Narock et al., 2019). Early Career Hydrologists may benefit from considering and discussing the role of preprints in shaping scientific discovery and career trajectories. Here we introduce preprints, offering Early Career Hydrologists with a variety of thoughts on the advantages and disadvantages of using preprints in research workflows, and providing tips and resources for learning more. If we missed an aspect of the preprint discussion that you feel passionate about or still have questions about, please feel free to reach out to Sheila (at [sheilasaia](https://twitter.com/sheilasaia?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)) and the Young Hydrology Society (YHS; at [YoungHydrology](https://twitter.com/younghydrology?lang=en)) on Twitter.

# What is a preprint?

A preprint refers to a research product (typically a research article) that is made publicly available before or at the same time it goes to peer review. A preprint server refers to an open access website where authors can submit and manage versions of their preprints. 

Some preprint servers such as European Geophysical Union (EGU) sponsored [Hydrology and Earth Systems Science (HESS) Discussions](https://www.hydrol-earth-syst-sci-discuss.net/discussion_papers.html) is affiliated with EGU’s HESS journal. Additionally, the American Geophysical Union (AGU) sponsored Earth and Space Science Open Archive (ESSOAr) preprint server is associated with AGU-affiliated journals. These journal-supported preprint servers offer a convenient publishing pipeline should the author’s work be accepted after peer review. 

Other preprint servers are not affiliated with a particular journal (e.g., [EarthArXiv](https://eartharxiv.org/), and [bioRxiv](https://www.biorxiv.org/). If an authors’ article is accepted for publication to a partner journal, these servers may offer transfer services for authors. For example, the bioRxiv offers transfer services to several journals including Applied and Environmental Microbiology (see details [here](https://www.biorxiv.org/about-biorxiv)). Preprint servers are typically not-for-profit (e.g., arXiv, bioRxiv, EarthArXiv); it is always good to check a preprint server’s not-for-profit status before submitting a preprint. See the ‘Things to Consider before Sharing a Preprint’ discussion below for more information.

# Advantages:

- Depending on the preprints server, authors may be given a digital object identifier (DOI) number that can be used to cite their work. Also, the preprint server manages the storage and versions of the preprint free of charge. The DOI allows others to cite, and ultimately, give authors credit for their ideas and work.

- The preprint (and eventually a postprint, if accepted by a journal) can be shared more broadly. This is especially true of the final publication, since a journal subscription is not required.

- Preprints improve the transparency of the peer review process by enabling readers to view article versions at each step of the review process; and thus, assess changes they’ve made.

- Preprint servers enable discussions between authors and interested parties. Readers can contribute to and look through these discussions via preprint server commenting features and direct communication with authors.

- Posting a preprint allows author share so-called ‘negative results’, which may improve future studies and conserving future time and funding resources (van Emmerik et al. 2018)

- Preprints may help streamline collaborations by avoiding or improving studies in different locations that address similar research goals.

- Preprint servers empower scientists to take control of the timeline for making their results public (Schloss 2017). This might prove especially helpful to overcoming current limitations of peer review (e.g., gender bias; Grogan 2019).

- Preprints can help facilitate research findings to the public domain, so as to stimulate interactions and collaborations with fellow researchers. This may be especially helpful for Earth Career Scientists looking for potential collaborators inside and outside of their field.

- Earth Career Scientists may be able to use preprints in grant and job applications to present progress and preliminary results. For example, the US National Institutes of Health allows scientists to include preprints in grant proposals (Kaiser 2017a, 2017b).

- Some disciplines (e.g., physics) use preprint servers to stake claim to their results (or at least have a DOI associated with their early work).

# Disadvantages:

- The discussion of preprint disadvantages largely centers around the fact that preprints are not validated by peer review (Kaiser 2017b). Researchers can make claims, that may be cited by others, without valid data supporting those claims. This may become especially problematic at the interface of science and the general public, especially if the general public and media representatives do not understand that the preprint is not peer reviewed.

- Another common criticism of preprints centers around fear of being “scooped”—when an author’s work is stolen before it can be published. [On the other hand, authors of preprints have a DOI. Also, some journals have announced “scooping protection” (Kaiser 2017b).]

- Researchers that post preprints need to do their homework before making their work public. See the ‘Things to Consider before Sharing a Preprint’ discussion below. Most notably, it is important that authors know what their journal-of-choice’s preprint policies are in terms of accepting preprints, type of preprint licenses, and preprint server funding structures (i.e., non-for-profit) that are allowed.

# Things to Consider Before Sharing a Preprint

1. Check whether the journal you are planning to submit your work to accepts preprints. You can check a journal’s preprint policy on [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/index.php). Many journals accept preprints posted on not-for-profit preprint servers, but it is best to confirm that this is the case. When in doubt, you can email the editor to clarify the journal’s preprint policy. In addition to the funding structure of the preprint server (e.g., not-for-profit), be sure to pay attention to the journal’s policies related to licenses that are assigned by the preprint servers (e.g., CC BY).

2. Ask your co-authors for permission to post your article as a preprint, which includes asking them about their institution’s or company’s preprint policy. Before you post, you want to make sure everyone agrees to post your article as a preprint. 

3. Make sure your article is ready to be posted as a preprint. Once your preprint is in the public domain, it will be very hard to remove.

# Where can I post and/or read a hydrology preprint?

- The [arXiv](https://arxiv.org/) is the oldest preprint server to-date (since 1991) and hosts research from physics, mathematics, computer science, statistics, engineering, and various other disciplines that interface with the hydrologic sciences. As of May 2019 (when this post was written), there were 241 arXiv search results for “hydrology” (0.02% of the entire collection). 

- Inspired by the arXiv, researchers established the [EarthArXiv](https://eartharxiv.org/) in 2017 to serve the earth sciences community; thus, hydrology is particularly well represented here. EarthArXiv is part of the [Open Science Framework (OSF)](https://osf.io/) initiative. 

- Last but not least, the [Earth and Space Science Open Archive (ESSOAr)](https://www.essoar.org/) preprint server was established in 2018 through a joint effort with the American Geophysical Union (AGU) and [Atypon](https://www.atypon.com/). ESSOAr is especially well suited for research that will be submitted to AGU-affiliated journals.

# Can (and how do) I cite a preprint?
As mentioned above, preprints need to be treated as unpublished, non-peer reviewed publications. As an author and reader, you need to assess the validity and quality of the work before you cite a preprint. Before submitting an article that cites preprinted work, you should check that the journal allows preprint citations. If the journal allows preprints, authors should adhere to the formatting guidelines to make it clear to reviewers/readers that the work is not peer-reviewed. The same goes for funding agencies. An example policy on how to cite preprints can be found for Nature-affiliated journals at https://www.nature.com/authors/policies/preprints.html.

# References
Grogan, K. 2019. How the entire scientific community can confront gender bias in the workplace. Nature Ecology & Evolution. 3:3-6. Accessed online at: https://www.nature.com/articles/s41559-018-0747-4

Kaiser, J. 2017a. NIH enables investigators to include draft preprints in grant proposals. Science. Mar. 24, 2017. Accessed online at: https://www.sciencemag.org/news/2017/03/nih-enables-investigators-include-draft-preprints-grant-proposals

Kaiser, J. 2017b. The preprint dilemma. Science. 357(6358):1344-1349. Available online at: https://science.sciencemag.org/content/357/6358/1344

Narock, T., E. Goldstein, C. Jackson, A. Bubeck, A. Enright, J. Farquharson, et al. Earth Science is Ready for Preprints. Eos. Apr. 23, 2019. Available online at: https://eartharxiv.org/kftsv/ and https://eos.org/project-updates/earth-science-is-ready-for-preprints

Schloss, P. D. 2017. Preprinting Microbiology. mbio. 8:e00438-17. Available online at: https://mbio.asm.org/content/8/3/e00438-17

van Emmerik, T., A. Popp, A. Solcerova, H. Muller, and R. Hut. 2018. Reporting negative results to stimulate experimental hydrology: discussion of “The role of experimental work in hydrological sciences - insights from a community survey”. Hydrological Sciences Journal. 63:1269-1273. https://doi.org/10.1080/02626667.2018.1493203. Available online at: https://eartharxiv.org/jhrfb/

# Additional Reading on Preprints
Nature Geosciences (editorial). 2018. ArXives of Earth Science. Nature Geosciences. 11: 149. Available online at: https://www.nature.com/articles/s41561-018-0083-y

ESSOAr FAQs: https://www.essoar.org/faq

PLOS Preprint Resources: https://www.plos.org/preprints

# Additional Thoughts
This post is meant to provide introductory information to early career hydrologists interested in sharing their work publicly via preprint. At this time, I've only submitted one paper for preprint; therefore, I'm inexperienced. It'd be interesting to hear from other early career scientists about how they've negotiated publication of preprints with more established scientists, particularly when it addressing points listed under 'Disadvantages' above.