---
title: "R Resources for Water Scientists"
author: "Sheila Saia"
date: '2019-02-14'
categories: ["R"]
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE, warning = FALSE)
```

# Background

There are lots of resources out there for R users and I thought it might be helpful to compile some that might be especially helpful for **water scientists**. I'll also admit that this is a 50% selfish task meant to help me keep track of resources for my own learning.

# Goals of This Post

The main goal of this blog post is to compile links to `R` resources including: packages, tutorials, books, etc. that might be of interests to water scientists.

Note to self that someday maybe I can update this post to also include `Python` resources. For now, I'm sticking to `R`.

Special thanks to all of the people who've worked hard to share their code and insights together to benefit us all. I love the open source programming community!

# R Packages

- Water-related packages currated by [Sam Zipper](https://samzipper.weebly.com/) at this Google Sheet document [here](https://docs.google.com/document/d/1XM3KuWdMgVrh92zE-CGIFNC7jYd_DGD8CokAVLkItz0/edit).

- CRAN tasks views for R packages related to [envirometrics](https://cran.r-project.org/web/views/Environmetrics.html), [hyrdrology](https://cran.r-project.org/web/views/Hydrology.html), [spatial analysis](https://cran.r-project.org/web/views/Spatial.html), [time series analysis](https://cran.r-project.org/web/views/TimeSeries.html), and [a number of other topics](https://cran.r-project.org/web/views/).


# Tutorials

- Vignettes for the `sf` package [(link)](https://github.com/r-spatial/sf)

- Vignettes for the `tidycensus` package [(link)](https://github.com/walkerke/tidycensus/tree/master/vignettes)

- USGS introduction to R tutorials [(link)](https://owi.usgs.gov/R/training-curriculum/intro-curriculum/)

- USGS R package use tutorials [(link)](https://owi.usgs.gov/R/training-curriculum/usgs-packages/)

- USGS R package development tutorial [(link)](https://owi.usgs.gov/R/training-curriculum/r-package-dev/)

- USGS other R training [(link)](https://owi.usgs.gov/R/training-curriculum/course-specific-material/)

- SESYNC R tutorials [(link)](https://cyberhelp.sesync.org/lesson/)

- Software Carpentry introduction to R tutorial [(link)](http://swcarpentry.github.io/r-novice-inflammation/)

- NEON R tutorials [(link)](https://www.neonscience.org/resources/data-tutorials)


# Blogs

- Blog by Jesse Sadler [(link)](https://www.jessesadler.com/)

- RGeo Blog by Matt Strimas-Mackey [(link)](http://strimas.com/#posts)

- Rivers & Ranids Blog by Ryan Peek [(link)](https://ryanpeek.github.io/)

- SESYNC Blog by various [(link)](https://cyberhelp.sesync.org/blog/)


# Books

- *R for Data Science* by Hadley Wickham & Garrett Grolemund [(link)](https://r4ds.had.co.nz/)

- *Spatial Data Science with R* by various [(link)](https://www.rspatial.org/)

- *Spatial Data Science* by Edzer Pebesma & Roger Bivand [(link)](https://keen-swartz-3146c4.netlify.com/index.html)

- *Geocomputation with R* by Robin Lovelace, Jakub Nowosad, and Jannes Muenchow [(link)](https://geocompr.robinlovelace.net/)

- *Applied Spatial Data Analysis with R* by Roger Bivand, Edzer Pebesma, and Virgilio Gómez-Rubio [(link)](http://gis.humboldt.edu/OLM/r/Spatial%20Analysis%20With%20R.pdf)

- *Fundamentals of Data Visualization* by Claus O. Wilke [(link)](https://serialmentor.com/dataviz/)

- *Happy Git and GitHub for the useR* by Jenny Bryan [(link)](https://happygitwithr.com/index.html)

- *Blogdown* by Yihui Xie, Amber Thomas, and Alison Presmanes Hill [(link)](https://bookdown.org/yihui/blogdown/)

- *rOpenSci Package Development, Maintenance, and Peer Review* by Brooke Anderson, Scott Chamberlain, Anna Krystalli, Lincoln Mullen, Karthik Ram, Noam Ross, Maëlle Salmon, and Melina Vidoni [(link)](https://ropensci.github.io/dev_guide/)

- Other cool books by RStudio staff [(link)](https://www.rstudio.com/resources/training/books/)


# Other Help

- rstudio::conf 2018 slides & recorded talks [(link)](https://github.com/simecek/RStudioConf2018Slides) or [(link)](https://resources.rstudio.com/rstudio-conf-2018)

- rstudio::conf 2019 slides & recorded talks (*coming soon*)

- Others have created similar summaries of R resources such as [this post by Steph Locke](https://itsalocke.com/blog/r-spatial-resources/) and [this page by R-Spatial Ladies](https://github.com/rspatialladies/rspatial-resources). 


If you know of any resources that I may have missed (it's very likely that I missed somehting!) please contact me!

